- name: set interface facts from file
  ansible.builtin.set_fact:
    intf_config: "{{ ((lookup('file','{{ playbook_dir }}/vars/intf.yml')) | from_yaml) }}"

- name: update interface configuration
  cisco.ios.interfaces:
    config: "{{ item.parsed }}"
    state: replaced
  loop: "{{ intf_config.results }}"
  check_mode: true

- name: set l2 facts from file
  ansible.builtin.set_fact:
    l2_config: "{{ ((lookup('file','{{ playbook_dir }}/vars/l2.yml')) | from_yaml) }}"

- name: update l2_interface configuration
  cisco.ios.l2_interfaces:
    config: "{{ item.parsed }}"
    state: replaced
  loop: "{{ l2_config.results }}"
  check_mode: true
